# Generated by Django 2.2.6 on 2019-11-08 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetoparticipantes',
            name='a',
            field=models.CharField(default='', max_length=10),
        ),
    ]
