# Generated by Django 2.2.6 on 2019-10-24 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalAPP', '0002_auto_20191024_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='linkLates',
            new_name='link_lates',
        ),
    ]
