# Generated by Django 2.2.6 on 2019-10-24 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalAPP', '0003_auto_20191024_1454'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
    ]
