# Generated by Django 2.2.6 on 2019-11-11 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalAPP', '0003_remove_projetoparticipantes_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='data_publicacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
