# Generated by Django 2.2.6 on 2019-11-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalAPP', '0004_auto_20191110_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profileImgs'),
        ),
    ]
