# Generated by Django 2.2.6 on 2019-11-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalAPP', '0005_projeto_projetoparticipantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='categoria',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='titulo',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
