# Generated by Django 2.2.6 on 2019-11-12 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalAPP', '0006_noticia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(upload_to='noticiaImgs'),
        ),
    ]
