# Generated by Django 2.2.6 on 2019-11-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalAPP', '0007_auto_20191101_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(upload_to='projImgs'),
        ),
    ]
