# Generated by Django 2.2.6 on 2019-11-13 19:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalAPP', '0007_auto_20191112_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='participantes',
            field=models.ManyToManyField(related_name='participantes', to=settings.AUTH_USER_MODEL),
        ),
    ]
