# Generated by Django 2.2.6 on 2019-11-13 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalAPP', '0008_projeto_participantes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjetoParticipantes',
        ),
    ]
