# Generated by Django 2.2.6 on 2019-11-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalAPP', '0008_auto_20191101_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
