# Generated by Django 2.2.6 on 2019-11-14 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portalAPP', '0009_delete_projetoparticipantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='participantes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
