# Generated by Django 2.2.6 on 2019-12-01 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalAPP', '0012_auto_20191119_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='participantes',
        ),
        migrations.AddField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
